doctrine_migrations:
    migrations_paths:
        'App\Infrastructure\Persistence\Migration': '%kernel.project_dir%/src/Infrastructure/Persistence/Migration'
    enable_profiler: false
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    organize_migrations: 'BY_YEAR_AND_MONTH'
