# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Performance optimizations
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: false
        throw: false

when@dev:
    framework:
        php_errors:
            log: false
            throw: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        php_errors:
            log: false
            throw: false

when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            default_redis_provider: redis://localhost
        http_client:
            default_options:
                extra:
                    curl:
                        CURLOPT_TCP_NODELAY: 1
                        CURLOPT_TCP_FASTOPEN: 1
        php_errors:
            log: false
            throw: false
