nelmio_api_doc:
    documentation:
        info:
            title: Fruits and Vegetables API
            description: API for managing fruits and vegetables collections
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$) 